# Generated by Django 5.0.2 on 2024-03-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_blog_link_alter_blog_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="pub_date",
            field=models.DateField(),
        ),
    ]
