# Generated by Django 5.0.2 on 2024-02-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=250)),
                ("image", models.ImageField(upload_to="portfolio/images/")),
                ("link", models.URLField(blank=True)),
            ],
        ),
    ]
